# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created: Fri Oct 25 17:48:13 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(800, 600)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.edtPort = QtGui.QLineEdit(Form)
        self.edtPort.setObjectName(_fromUtf8("edtPort"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.edtPort)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.edtMaxMon = QtGui.QLineEdit(Form)
        self.edtMaxMon.setObjectName(_fromUtf8("edtMaxMon"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.edtMaxMon)
        self.horizontalLayout_3.addLayout(self.formLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.edtMinPres = QtGui.QLineEdit(Form)
        self.edtMinPres.setObjectName(_fromUtf8("edtMinPres"))
        self.gridLayout.addWidget(self.edtMinPres, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.edtMaxPres = QtGui.QLineEdit(Form)
        self.edtMaxPres.setObjectName(_fromUtf8("edtMaxPres"))
        self.gridLayout.addWidget(self.edtMaxPres, 0, 4, 1, 1)
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 2, 3, 1, 1)
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 3, 1, 1, 1)
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 3, 3, 1, 1)
        self.edtMinTemp = QtGui.QLineEdit(Form)
        self.edtMinTemp.setObjectName(_fromUtf8("edtMinTemp"))
        self.gridLayout.addWidget(self.edtMinTemp, 1, 2, 1, 1)
        self.edtMaxTemp = QtGui.QLineEdit(Form)
        self.edtMaxTemp.setObjectName(_fromUtf8("edtMaxTemp"))
        self.gridLayout.addWidget(self.edtMaxTemp, 1, 4, 1, 1)
        self.edtMinOxi = QtGui.QLineEdit(Form)
        self.edtMinOxi.setObjectName(_fromUtf8("edtMinOxi"))
        self.gridLayout.addWidget(self.edtMinOxi, 2, 2, 1, 1)
        self.edtMaxOxi = QtGui.QLineEdit(Form)
        self.edtMaxOxi.setObjectName(_fromUtf8("edtMaxOxi"))
        self.gridLayout.addWidget(self.edtMaxOxi, 2, 4, 1, 1)
        self.edtMinFc = QtGui.QLineEdit(Form)
        self.edtMinFc.setObjectName(_fromUtf8("edtMinFc"))
        self.gridLayout.addWidget(self.edtMinFc, 3, 2, 1, 1)
        self.edtMaxFc = QtGui.QLineEdit(Form)
        self.edtMaxFc.setObjectName(_fromUtf8("edtMaxFc"))
        self.gridLayout.addWidget(self.edtMaxFc, 3, 4, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtGui.QSpacerItem(20, 317, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Configurações", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Porta de conexão", None, QtGui.QApplication.UnicodeUTF8))
        self.edtPort.setText(QtGui.QApplication.translate("Form", "65000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Máximo de monitores", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMaxMon.setText(QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Alarmes Gerais", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Mínimo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "SPO2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Mínimo", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMinPres.setText(QtGui.QApplication.translate("Form", "90/70", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Máximo", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMaxPres.setText(QtGui.QApplication.translate("Form", "140/90", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Temperatura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Máximo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Pressão", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Mínimo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Máximo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Frequência Cardíaca", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Mínimo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Máximo", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMinTemp.setText(QtGui.QApplication.translate("Form", "35", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMaxTemp.setText(QtGui.QApplication.translate("Form", "38", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMinOxi.setText(QtGui.QApplication.translate("Form", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMaxOxi.setText(QtGui.QApplication.translate("Form", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMinFc.setText(QtGui.QApplication.translate("Form", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMaxFc.setText(QtGui.QApplication.translate("Form", "95", None, QtGui.QApplication.UnicodeUTF8))

