# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solo_monitor.ui'
#
# Created: Tue Oct 29 20:19:27 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SoloMonitForm(object):
    def setupUi(self, SoloMonitForm):
        SoloMonitForm.setObjectName(_fromUtf8("SoloMonitForm"))
        SoloMonitForm.resize(676, 506)
        self.verticalLayout_3 = QtGui.QVBoxLayout(SoloMonitForm)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.imgPaciente = QtGui.QLabel(SoloMonitForm)
        self.imgPaciente.setText(_fromUtf8(""))
        self.imgPaciente.setPixmap(QtGui.QPixmap(_fromUtf8("icones/img_paciente.png")))
        self.imgPaciente.setObjectName(_fromUtf8("imgPaciente"))
        self.horizontalLayout_7.addWidget(self.imgPaciente)
        self.lbPaciente = QtGui.QLabel(SoloMonitForm)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbPaciente.setFont(font)
        self.lbPaciente.setText(_fromUtf8(""))
        self.lbPaciente.setObjectName(_fromUtf8("lbPaciente"))
        self.horizontalLayout_7.addWidget(self.lbPaciente)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.parametrosPanel = QtGui.QWidget(SoloMonitForm)
        self.parametrosPanel.setStyleSheet(_fromUtf8(""))
        self.parametrosPanel.setObjectName(_fromUtf8("parametrosPanel"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.parametrosPanel)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.parametrosPanel)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("icones/ecg_white.png")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.parametrosPanel)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.ecgchart = PlotWidget(self.parametrosPanel)
        self.ecgchart.setObjectName(_fromUtf8("ecgchart"))
        self.horizontalLayout_8.addWidget(self.ecgchart)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.imgPressao = QtGui.QLabel(self.parametrosPanel)
        self.imgPressao.setText(_fromUtf8(""))
        self.imgPressao.setPixmap(QtGui.QPixmap(_fromUtf8("icones/pressao_white.png")))
        self.imgPressao.setObjectName(_fromUtf8("imgPressao"))
        self.horizontalLayout_4.addWidget(self.imgPressao)
        self.lbPressao = QtGui.QLabel(self.parametrosPanel)
        self.lbPressao.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbPressao.setFont(font)
        self.lbPressao.setStyleSheet(_fromUtf8("color: rgb(245, 232, 46);"))
        self.lbPressao.setText(_fromUtf8(""))
        self.lbPressao.setAlignment(QtCore.Qt.AlignCenter)
        self.lbPressao.setMargin(10)
        self.lbPressao.setObjectName(_fromUtf8("lbPressao"))
        self.horizontalLayout_4.addWidget(self.lbPressao)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.imgO2 = QtGui.QLabel(self.parametrosPanel)
        self.imgO2.setText(_fromUtf8(""))
        self.imgO2.setPixmap(QtGui.QPixmap(_fromUtf8("icones/spo_white.png")))
        self.imgO2.setObjectName(_fromUtf8("imgO2"))
        self.horizontalLayout_3.addWidget(self.imgO2)
        self.lbO2 = QtGui.QLabel(self.parametrosPanel)
        self.lbO2.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbO2.setFont(font)
        self.lbO2.setStyleSheet(_fromUtf8("color:rgb(124, 188, 255)"))
        self.lbO2.setText(_fromUtf8(""))
        self.lbO2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbO2.setMargin(10)
        self.lbO2.setObjectName(_fromUtf8("lbO2"))
        self.horizontalLayout_3.addWidget(self.lbO2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.imgTemperatura = QtGui.QLabel(self.parametrosPanel)
        self.imgTemperatura.setText(_fromUtf8(""))
        self.imgTemperatura.setPixmap(QtGui.QPixmap(_fromUtf8("icones/temp_white.png")))
        self.imgTemperatura.setObjectName(_fromUtf8("imgTemperatura"))
        self.horizontalLayout_5.addWidget(self.imgTemperatura)
        self.lbTemperatura = QtGui.QLabel(self.parametrosPanel)
        self.lbTemperatura.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbTemperatura.setFont(font)
        self.lbTemperatura.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.lbTemperatura.setText(_fromUtf8(""))
        self.lbTemperatura.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTemperatura.setMargin(10)
        self.lbTemperatura.setObjectName(_fromUtf8("lbTemperatura"))
        self.horizontalLayout_5.addWidget(self.lbTemperatura)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.imgFC = QtGui.QLabel(self.parametrosPanel)
        self.imgFC.setText(_fromUtf8(""))
        self.imgFC.setPixmap(QtGui.QPixmap(_fromUtf8("icones/fc _white.png")))
        self.imgFC.setObjectName(_fromUtf8("imgFC"))
        self.horizontalLayout_2.addWidget(self.imgFC)
        self.lbFC = QtGui.QLabel(self.parametrosPanel)
        self.lbFC.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbFC.setFont(font)
        self.lbFC.setStyleSheet(_fromUtf8("color: rgb(255, 165, 21);"))
        self.lbFC.setText(_fromUtf8(""))
        self.lbFC.setAlignment(QtCore.Qt.AlignCenter)
        self.lbFC.setMargin(10)
        self.lbFC.setObjectName(_fromUtf8("lbFC"))
        self.horizontalLayout_2.addWidget(self.lbFC)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.parametrosPanel)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnalarm = QtGui.QPushButton(SoloMonitForm)
        self.btnalarm.setEnabled(True)
        self.btnalarm.setObjectName(_fromUtf8("btnalarm"))
        self.horizontalLayout_6.addWidget(self.btnalarm)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.alarmePanel = QtGui.QWidget(SoloMonitForm)
        self.alarmePanel.setObjectName(_fromUtf8("alarmePanel"))
        self.verticalLayout_3.addWidget(self.alarmePanel)

        self.retranslateUi(SoloMonitForm)
        QtCore.QMetaObject.connectSlotsByName(SoloMonitForm)

    def retranslateUi(self, SoloMonitForm):
        SoloMonitForm.setWindowTitle(QtGui.QApplication.translate("SoloMonitForm", "Monitor de Sinais Vitais", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SoloMonitForm", "ECG", None, QtGui.QApplication.UnicodeUTF8))
        self.btnalarm.setText(QtGui.QApplication.translate("SoloMonitForm", "Alarmes Individuais", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
