# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solo_monitor.ui'
#
# Created: Fri Oct 25 19:12:36 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SoloMonitForm(object):
    def setupUi(self, SoloMonitForm):
        SoloMonitForm.setObjectName(_fromUtf8("SoloMonitForm"))
        SoloMonitForm.resize(694, 516)
        self.gridLayout_4 = QtGui.QGridLayout(SoloMonitForm)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_alarms = QtGui.QGridLayout()
        self.gridLayout_alarms.setObjectName(_fromUtf8("gridLayout_alarms"))
        self.label_29 = QtGui.QLabel(SoloMonitForm)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_alarms.addWidget(self.label_29, 2, 1, 1, 1)
        self.label_30 = QtGui.QLabel(SoloMonitForm)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_alarms.addWidget(self.label_30, 2, 0, 1, 1)
        self.label_31 = QtGui.QLabel(SoloMonitForm)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_alarms.addWidget(self.label_31, 0, 1, 1, 1)
        self.edtMinPres_3 = QtGui.QLineEdit(SoloMonitForm)
        self.edtMinPres_3.setObjectName(_fromUtf8("edtMinPres_3"))
        self.gridLayout_alarms.addWidget(self.edtMinPres_3, 0, 2, 1, 1)
        self.label_32 = QtGui.QLabel(SoloMonitForm)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_alarms.addWidget(self.label_32, 0, 3, 1, 1)
        self.edtMaxPres_3 = QtGui.QLineEdit(SoloMonitForm)
        self.edtMaxPres_3.setObjectName(_fromUtf8("edtMaxPres_3"))
        self.gridLayout_alarms.addWidget(self.edtMaxPres_3, 0, 4, 1, 1)
        self.label_33 = QtGui.QLabel(SoloMonitForm)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_alarms.addWidget(self.label_33, 1, 0, 1, 1)
        self.label_34 = QtGui.QLabel(SoloMonitForm)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_alarms.addWidget(self.label_34, 1, 3, 1, 1)
        self.label_36 = QtGui.QLabel(SoloMonitForm)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_alarms.addWidget(self.label_36, 1, 1, 1, 1)
        self.label_37 = QtGui.QLabel(SoloMonitForm)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_alarms.addWidget(self.label_37, 2, 3, 1, 1)
        self.label_38 = QtGui.QLabel(SoloMonitForm)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_alarms.addWidget(self.label_38, 3, 0, 1, 1)
        self.label_39 = QtGui.QLabel(SoloMonitForm)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_alarms.addWidget(self.label_39, 3, 1, 1, 1)
        self.label_40 = QtGui.QLabel(SoloMonitForm)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_alarms.addWidget(self.label_40, 3, 3, 1, 1)
        self.edtMinTemp_3 = QtGui.QLineEdit(SoloMonitForm)
        self.edtMinTemp_3.setObjectName(_fromUtf8("edtMinTemp_3"))
        self.gridLayout_alarms.addWidget(self.edtMinTemp_3, 1, 2, 1, 1)
        self.edtMaxTemp_3 = QtGui.QLineEdit(SoloMonitForm)
        self.edtMaxTemp_3.setObjectName(_fromUtf8("edtMaxTemp_3"))
        self.gridLayout_alarms.addWidget(self.edtMaxTemp_3, 1, 4, 1, 1)
        self.edtMinOxi_3 = QtGui.QLineEdit(SoloMonitForm)
        self.edtMinOxi_3.setObjectName(_fromUtf8("edtMinOxi_3"))
        self.gridLayout_alarms.addWidget(self.edtMinOxi_3, 2, 2, 1, 1)
        self.edtMaxOxi_3 = QtGui.QLineEdit(SoloMonitForm)
        self.edtMaxOxi_3.setObjectName(_fromUtf8("edtMaxOxi_3"))
        self.gridLayout_alarms.addWidget(self.edtMaxOxi_3, 2, 4, 1, 1)
        self.edtMinFc_3 = QtGui.QLineEdit(SoloMonitForm)
        self.edtMinFc_3.setObjectName(_fromUtf8("edtMinFc_3"))
        self.gridLayout_alarms.addWidget(self.edtMinFc_3, 3, 2, 1, 1)
        self.edtMaxFc_3 = QtGui.QLineEdit(SoloMonitForm)
        self.edtMaxFc_3.setObjectName(_fromUtf8("edtMaxFc_3"))
        self.gridLayout_alarms.addWidget(self.edtMaxFc_3, 3, 4, 1, 1)
        self.label_35 = QtGui.QLabel(SoloMonitForm)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_alarms.addWidget(self.label_35, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_alarms, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnalarm = QtGui.QPushButton(SoloMonitForm)
        self.btnalarm.setEnabled(True)
        self.btnalarm.setObjectName(_fromUtf8("btnalarm"))
        self.horizontalLayout_6.addWidget(self.btnalarm)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ecgchart = PlotWidget(SoloMonitForm)
        self.ecgchart.setObjectName(_fromUtf8("ecgchart"))
        self.horizontalLayout_2.addWidget(self.ecgchart)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblbpm = QtGui.QLabel(SoloMonitForm)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblbpm.setFont(font)
        self.lblbpm.setObjectName(_fromUtf8("lblbpm"))
        self.horizontalLayout.addWidget(self.lblbpm)
        self.lblspo = QtGui.QLabel(SoloMonitForm)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblspo.setFont(font)
        self.lblspo.setObjectName(_fromUtf8("lblspo"))
        self.horizontalLayout.addWidget(self.lblspo)
        self.lblnibp = QtGui.QLabel(SoloMonitForm)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblnibp.setFont(font)
        self.lblnibp.setObjectName(_fromUtf8("lblnibp"))
        self.horizontalLayout.addWidget(self.lblnibp)
        self.lbltemp = QtGui.QLabel(SoloMonitForm)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbltemp.setFont(font)
        self.lbltemp.setObjectName(_fromUtf8("lbltemp"))
        self.horizontalLayout.addWidget(self.lbltemp)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(SoloMonitForm)
        QtCore.QMetaObject.connectSlotsByName(SoloMonitForm)

    def retranslateUi(self, SoloMonitForm):
        SoloMonitForm.setWindowTitle(QtGui.QApplication.translate("SoloMonitForm", "Monitor de Sinais Vitais", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("SoloMonitForm", "Mínimo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("SoloMonitForm", "SPO2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("SoloMonitForm", "Mínimo", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMinPres_3.setText(QtGui.QApplication.translate("SoloMonitForm", "90/70", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("SoloMonitForm", "Máximo", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMaxPres_3.setText(QtGui.QApplication.translate("SoloMonitForm", "140/90", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("SoloMonitForm", "Temperatura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("SoloMonitForm", "Máximo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("SoloMonitForm", "Mínimo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("SoloMonitForm", "Máximo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("SoloMonitForm", "Frequência Cardíaca", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("SoloMonitForm", "Mínimo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("SoloMonitForm", "Máximo", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMinTemp_3.setText(QtGui.QApplication.translate("SoloMonitForm", "35", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMaxTemp_3.setText(QtGui.QApplication.translate("SoloMonitForm", "38", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMinOxi_3.setText(QtGui.QApplication.translate("SoloMonitForm", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMaxOxi_3.setText(QtGui.QApplication.translate("SoloMonitForm", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMinFc_3.setText(QtGui.QApplication.translate("SoloMonitForm", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMaxFc_3.setText(QtGui.QApplication.translate("SoloMonitForm", "95", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("SoloMonitForm", "Pressão", None, QtGui.QApplication.UnicodeUTF8))
        self.btnalarm.setText(QtGui.QApplication.translate("SoloMonitForm", "Alarmes", None, QtGui.QApplication.UnicodeUTF8))
        self.lblbpm.setText(QtGui.QApplication.translate("SoloMonitForm", "fc: 120 bpm", None, QtGui.QApplication.UnicodeUTF8))
        self.lblspo.setText(QtGui.QApplication.translate("SoloMonitForm", "spo2: 98%", None, QtGui.QApplication.UnicodeUTF8))
        self.lblnibp.setText(QtGui.QApplication.translate("SoloMonitForm", "nibp: 120/80", None, QtGui.QApplication.UnicodeUTF8))
        self.lbltemp.setText(QtGui.QApplication.translate("SoloMonitForm", "temp: 36,5 ºC", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
